# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'destination.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMessageBox, QLabel
from PyQt5.QtSql import QSqlDatabase, QSqlQuery


class Ui_DestinationWindow(object):

    def loadData(self):
        conn = QSqlDatabase.addDatabase('QSQLITE')
        conn.setDatabaseName('ex1')
        temp = 'destination'
        if not conn.open():
            QtWidgets.QMessageBox.critical(
                None,
                "แจ้งเตือน",
                "ERROR ติดต่อฐานข้อมูลไม่ได้ : %s" % conn.lastError().databaseText(),
            )
            sys.exit(1)
        #query = 'SELECT * FROM destination'
        query = QSqlQuery()
        query.exec(
            f"""
            SELECT * FROM {temp}
            """
        )

    def setupUi(self, DestinationWindow):
        DestinationWindow.setObjectName("DestinationWindow")
        DestinationWindow.resize(300, 300)
        self.centralwidget = QtWidgets.QWidget(DestinationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(100, 230, 89, 41))
        self.btn_save.setObjectName("btn_save")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 260, 200))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        DestinationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DestinationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        DestinationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DestinationWindow)
        self.statusbar.setObjectName("statusbar")
        DestinationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DestinationWindow)
        QtCore.QMetaObject.connectSlotsByName(DestinationWindow)

        self.loadData()

    def retranslateUi(self, DestinationWindow):
        _translate = QtCore.QCoreApplication.translate
        DestinationWindow.setWindowTitle(_translate("DestinationWindow", "Destination Setting"))
        self.btn_save.setText(_translate("DestinationWindow", "SAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DestinationWindow = QtWidgets.QMainWindow()
    ui = Ui_DestinationWindow()
    ui.setupUi(DestinationWindow)
    DestinationWindow.show()
    sys.exit(app.exec_())
